name: say hello
on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: the messager
      run: echo "hola fran"
